fixed onchange scripts

diff --git a/run_onchange_install-packages.sh.tmpl b/run_onchange_install-packages.sh.tmpl
--- a/run_onchange_install-packages.sh.tmpl
+++ b/run_onchange_install-packages.sh.tmpl
@@ -9,6 +9,10 @@ get_version() {
 add_microsoft_repo() {
   # todo: make it conditional
   # check that repo is not already added
+  ## Since we use asdf to get dotnet now, we don't need to add the microsoft repo
+  ## if we want to use it again we need to get the distro aswell as the version.
+  ## it fails on debian.
+  return
 
   local version="$(get_version)"
   # Download Microsoft signing key and repository
@@ -33,8 +37,6 @@ install_packages() {
       python3-pip \
       pipx \
       python3-pygments \
-      keychain \
-      build-essential \
       procps \
       curl \
       file \
@@ -46,8 +48,10 @@ install_packages() {
     sudo apt-get install -y \
       socat
   {{- end}}
-  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+
+  if ! command -v brew &> /dev/null; then
+    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+  fi
 }
 
-add_microsoft_repo
 install_packages
